version: v1

labels:
  - label: 'feat'
    include:
      title: '^feat:.*'
      branch: '^feat/.*'
      commits: '^feat:.*'

  - label: dependabot
    include:
      title: '^chore(deps).*'
      branch: '^dependabot/.*'
      commits: '^chore(deps).*'

  - label: 'fix'
    include:
      title: '^fix:.*'
      branch: '^fix/.*'
      commits: '^fix:.*'

  - label: 'chore'
    include:
      title: "^chore(\\((deps|ci)\\))?:.*"
      branch: '^chore/.*'
      commits: "^chore(\\((deps|ci)\\))?:.*"

  - label: 'chore'
    include:
      title: "^bump(\\((deps|ci)\\))?:.*"

  - label: 'docs'
    include:
      title: '^docs:.*'
      branch: '^docs/.*'
      commits: '^docs:.*'

  - label: 'test:labeler'
    sync: true
    include:
      files: '.github/labeler.yml'

  - label: 'test:dist'
    sync: true
    include:
      files: ['dist/*']

  - label: 'test:tests'
    sync: true
    include:
      files: ['__tests__/matcher/**', '__tests__/*.ts']

  - label: 'test:body'
    include:
      body: "(\\n|.)*- \\[x\\] test(\\n|.)*"

  - label: 'test:comment'
    include:
      comment: "# \\[Codecov\\] .*"

  - label: 'test:stale'
    include:
      comment: '/stale'

  - label: 'test: s'
    sync: true
    include:
      files:
        count:
          gte: 1
          lte: 4

  - label: 'test: m'
    sync: true
    include:
      files:
        count:
          gte: 5
          lte: 10

  - label: 'test: l'
    sync: true
    include:
      files:
        count:
          gte: 11

  - label: 'Maintainer'
    include:
      author:
        - fuxingloh

  - label: 'Owner'
    include:
      author: fuxingloh

  - label: 'branch: main'
    include:
      baseBranch: main

  - label: 'branch: release'
    include:
      baseBranch: '^release/.*'

checks:
  - context: 'Semantic Pull Request'
    url: 'https://github.com/fuxingloh/multi-labeler/blob/main/.github/labeler.yml'
    description:
      success: Ready for review & merge.
      failure: Missing semantic label for merge.
    labels:
      any:
        - feat
        - fix
        - chore
        - docs

  - context: 'Do Not Merge'
    url: 'https://github.com/fuxingloh/multi-labeler/blob/main/.github/labeler.yml'
    description: "Disable merging when 'DO NOT MERGE' label is set"
    labels:
      none:
        - 'DO NOT MERGE'
