name: CI Package

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    environment: cest-la-v/auto-labels-action workflow
    steps:
      - uses: actions/checkout@v5.0.0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: '.bun-version'

      - run: bun install --frozen-lockfile
      - run: bun run package

      - id: app
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.WORKFLOW_APP_ID }}
          private_key: ${{ secrets.WORKFLOW_PRIVATE_KEY }}

      - uses: peter-evans/create-pull-request@v7.0.8
        with:
          token: ${{ steps.app.outputs.token }}
          commit-message: 'chore(ci): bun run package'
          title: 'chore(ci): bun run package'
          body: |
            #### What this PR does / why we need it:

            Updated `./dist/**` files with `bun run package`.

          branch: ci-package
