name: Dogfooding

on:
  pull_request:
    types: [opened, reopened, edited, synchronize, ready_for_review, labeled, unlabeled]
  issues:
    types: [opened, reopened]
  issue_comment:

permissions:
  contents: read
  issues: write
  pull-requests: write
  statuses: write

jobs:
  action:
    name: Auto Labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
