name: Release Tags

on:
  release:
    types: [released]

permissions:
  contents: write

jobs:
  release-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0

      - uses: vweevers/additional-tags-action@v2.0.0
